name: Wathab CI/CD Deployment

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}

    steps:
      # -------------------------------
      # Checkout
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Login to GitHub Container Registry
      # -------------------------------
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u ${{ github.actor }} --password-stdin

      # -------------------------------
      # Build & Push Docker Image
      # -------------------------------
      - name: Build and push Docker image
        env:
          SANITY_DATASET: ${{ vars.SANITY_DATASET }}
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.PROJECT_ID }} \
            --build-arg NEXT_PUBLIC_SANITY_DATASET=${SANITY_DATASET:-production} \
            -t ghcr.io/omnexa-technology/wathab:latest .
          docker push ghcr.io/omnexa-technology/wathab:latest

      # -------------------------------
      # Setup SSH
      # -------------------------------
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # -------------------------------
      # Deploy on server (NO BUILD)
      # -------------------------------
      - name: Deploy on server
        run: |
          ssh -o ServerAliveInterval=30 -o StrictHostKeyChecking=accept-new "${SERVER_USER}@${SERVER_IP}" "
            cd /home/wathab/apps/wathab
            docker compose pull
            docker compose up -d
          "